# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QdtZDw5uHzNWN60vx1fVEWyeS48ZqfEL
"""

# Step 1 Importing Libraries
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.preprocessing import LabelEncoder


# Part A
df = pd.read_csv("Dataset 2.csv")
df.head()
print('No. of Columns:')
print(len(df.columns))
print("")
print("No. of Rows:")
print(len(df))
print("")
print('Columns:')
print(df.columns)
print("")
print("")
numcol = df.select_dtypes(include = "number").columns
print("Numerical features are:")
print(numcol)
print("")
numcol2 = df.select_dtypes(include =[ "object","category"]).columns
print("Categorical features are:")
print(numcol2)
print(df.isna().sum())

# Part B
print(" Average age :",df["Age"].mean())
print("Average watch hours per week :",df['WatchHoursPerWeek'].mean())
print("Monthly Spend :",df["MonthlySpend"].mean())
print(df.groupby("SubscriptionType").count())
print(" \npercentage of users who renewed their subscriptions: ")
print((df["SubscriptionRenewed"]=="Yes").mean()*100)
print("")
print(int(numcol2))