# -*- coding: utf-8 -*-
"""Week2_Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFO-KOkaz7Or_UZkSyC1-Nz7q7Fo4gW1

# q1
1.Classification
2.Decision Tree

#q2
feature :- It is the individual ,measurable property or characterstic of your data that can be used by algorithms to make predictions.
label:- The columns which we want to see in our output.

#q3
the model reaches to this prediction by using the label data present in the dataset.

#q4
1.KNN is considered as supervised because it uses the label categorical data present in the dataset.
2.No

#q5
the prediction will be yes because in  KNN it return the prediction which is mostly come in the data.

#q6
x:-feature
y:-label
m:-slope
b:- intercept

#q7
It measures the strength and direction between the variables .
+1 represent positive correlation and -1 represent negative correlation .
Also in a correlation matrix values are in the range between -1 to +1.

#q8
1.False negative
2.This can be dangerous because:-
As the person is unaware about his medical condition he/she might go to that places were he/she shouldn't go ,
this will increase the chance for the spread of the disease .
Moreover the patient is relaxed and think that he is not suffering from any disease and due to this disease can be increased beyond a safe range .

#q9
1.It is a type of matrix which is use to determine the accuracy .
it uses  4 terms as its elements or we can say that in the matrix we have 4 numbers which is occupied on position like this
[True positive    false negative
 false positive  true negative ]
It predict values in range -1 to +1

2. Correlation matrix is used to measure the relationship between the variables and uses TP,FN,NP,FP
while the confusion matrix is used to find the accuracy .It predict values in range -1 to +1.

#q10
Decision Tree :- It predict on label categorical data and make prediction from the previous or known values.It basically give output in yes /no or as the user provide option in the form of some conditions .
KNN :- It predict on  categorical data and it can't  make prediction from the previous or known values.   
SVM :- It stand for Support V Machine . it is based on supervised learning Algorithm and it find best boundary between classes.

Linear Regression :- It give output in the form of numerical values . It predict data from the previous labelled data .
Neural Network :- It is a Machine Learning model inspired by human brain , which learn from the pattern from data by connecting some simple processing units called neurons .
"""