# -*- coding: utf-8 -*-
"""Week2_Assignment1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QdtZDw5uHzNWN60vx1fVEWyeS48ZqfEL
"""

from pandas.core.indexes.accessors import DatetimeAndPeriodProperties
# Step 1 Importing Libraries
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.preprocessing import LabelEncoder


# Part A
df = pd.read_csv("Dataset 2.csv")
df.head()
print('No. of Columns:')
print(len(df.columns))
print("")
print("No. of Rows:")
print(len(df))
print("")
print('Columns:')
print(df.columns)
print("")
print("")
numcol = df.select_dtypes(include = "number").columns
print("Numerical features are:")
print(numcol)
print("")
numcol2 = df.select_dtypes(include =[ "object","category"]).columns
print("Categorical features are:")
print(numcol2)
print(df.isna().sum())

# Part B
print(" Average age :",df["Age"].mean())
print("Average watch hours per week :",df['WatchHoursPerWeek'].mean())
print("Monthly Spend :",df["MonthlySpend"].mean())
print(df.groupby("SubscriptionType").count())
print(" \npercentage of users who renewed their subscriptions: ")
print((df["SubscriptionRenewed"]=="Yes").mean()*100)
print("")

# Part C
print("")
le = LabelEncoder()
df['Gender'] =le.fit_transform(df['Gender'] )

df['SubscriptionType']=le.fit_transform(df['SubscriptionType'])

df['FavoriteGenre']=le.fit_transform(df['FavoriteGenre'])

df['SubscriptionRenewed']=le.fit_transform(df['SubscriptionRenewed'])

x = df.drop(['UserID'],axis = 1)
y = df['SubscriptionRenewed']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

# Part D

dt = DecisionTreeClassifier(random_state=42)
dt.fit(x_train,y_train)
pred = dt.predict(x_test)
dtpred = accuracy_score(y_test,pred)
print('Decision Tree Accuracy:',dtpred)
print("")
print('Confusion matrix')
print(confusion_matrix(y_test,pred))

# Part E

kNN = KNeighborsClassifier(n_neighbors=5)
kNN.fit(x_train,y_train)
knn_pred = kNN.predict(x_test)
knnpred = accuracy_score(y_test,knn_pred)
print("KNN Accuracy :", knnpred)

# Part F

x_reg = df.drop(['UserID'],axis=1)
y_reg = df['MonthlySpend']
x_train_reg,x_test_reg,y_train_reg,y_test_reg = train_test_split(x_reg,y_reg,test_size=0.2,random_state=42)
lr = LinearRegression()
lr.fit(x_test_reg,y_test_reg)
amount  = lr.predict([[43,1,1,40,34,1,2,780,1]])
print('Monthly Spending',amount[0])

# Business Reflection Questions

if dtpred>knnpred:
  print('Decision Tree performed better')
else:
  print('KNN performed better')

"""Subscription Renewal is affected the most by Subscriptiontype , MonthlySpend

Subscription renewal is a classification problem as it depend on the label data

Monthly Spending is a Regression because it is based on numerical values or it gives numerical output

Platform can use  some rules and conditions for better predictions
"""