# -*- coding: utf-8 -*-
"""Week3_Assignment1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NworAZ7kkAXbP4ntya6VXFxeQQIGgi5T
"""

!pip install pandas --quiet
import pandas as pd

## Q1
df =pd.read_csv('Agri.csv')

print(df.shape)
print("Column :")
df.columns
df.head(10)

#Q2
print(df.info())
print(df.isnull().sum())

# Q3
print(df.describe())
print("highest mean :",df.mean(numeric_only=True).idxmax())
print("highest standard deviation :",df.std(numeric_only=True).idxmax())

# Commented out IPython magic to ensure Python compatibility.
# Q4
import plotly.express as px
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
df['rainfall_mm'].hist(bins = 3)
plt.xlabel('rainfall_mm')
plt.title('Rainfall')
plt.show()

df['temperature_c'].hist(bins = 3)
plt.xlabel('temperature_c')
plt.title('Temperature')
plt.show()

df['fertilizer_kg'].hist(bins = 3)
plt.xlabel('fertilizer_kg')
plt.title('fertilizer per kg')
plt.show()

df['yield_ton_per_hectare'].hist(bins = 3)
plt.xlabel('yield_ton_per_hectare  ')
plt.title('yield_ton per hectare  ')
plt.show()

#Q5
print(df.crop_type.value_counts())
df.crop_type.value_counts().plot(kind = "bar")
plt.show()
print("crop appears most frequently:  ",df['crop_type'].value_counts().idxmin())

#Q6
print(df["soil_type"].value_counts())
df.soil_type.value_counts().plot(kind = "bar")
print("soil type is most common:  ",df['soil_type'].value_counts().idxmax())

#Q7
px.histogram(df,x="yield_ton_per_hectare")
# 1. No the distribution is not normal
# 2. Yes there are some outliers which are noticeable

#Q8
# rainfall_mm has strong relationship with the yield
sns.scatterplot(data=df,x="rainfall_mm",y="yield_ton_per_hectare",alpha= 0.7,s=15)

sns.scatterplot(data=df,x="fertilizer_kg",y="yield_ton_per_hectare",alpha= 0.7,s=15)

#Q9
from sklearn.preprocessing import LabelEncoder
print(df.corr(numeric_only=True))
le = LabelEncoder()
df['crop_type']=le.fit_transform(df['crop_type'])
df['soil_type']=le.fit_transform(df['soil_type'])
# top features which are  most correlated with crop yield:- rainfall_mm,irrigation_hours,fertilizer_kg

sns.heatmap(df.corr(numeric_only=True),cmap= 'Reds',annot= True)

#Q10
print("crop_avg_yield :", df.groupby('crop_type')["yield_ton_per_hectare"].mean())
print("soil_avg_yield :", df.groupby('soil_type')["yield_ton_per_hectare"].mean())
print(df.groupby('crop_type')["yield_ton_per_hectare"].mean().idxmax())
print(df.groupby('soil_type')["yield_ton_per_hectare"].mean().idxmax())

#Q11
from sklearn.preprocessing import LabelEncoder
print(df.select_dtypes(include=['object','category']).columns)
le = LabelEncoder()
df['crop_type']=le.fit_transform(df['crop_type'])
df['soil_type']=le.fit_transform(df['soil_type'])
agri_encoded = pd.get_dummies(df,
                              columns=['rainfall_mm','temperature_c','fertilizer_kg','irrigation_hours','soil_ph','crop_type','soil_type','yield_ton_per_hectare'],
                              drop_first=True)
df.head()

#Q12
from sklearn.model_selection import train_test_split
X=df.drop(['soil_ph','temperature_c'],axis = 1)
y=df['yield_ton_per_hectare']

#Q13
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print(X_train.shape,
y_train.shape,
X_test.shape,
y_test.shape)

#Q14
from sklearn.linear_model import LinearRegression
X_reg=df.drop(['soil_ph','temperature_c'],axis = 1)
y_reg=df['yield_ton_per_hectare']
X_train_reg,X_test_reg,y_train_reg,y_test_reg=train_test_split(X_reg,y_reg,test_size=0.2,random_state=42)
lr=LinearRegression()
lr.fit(X_train_reg,y_train_reg)
yield_pred = lr.predict([[588,256,7,1,1,5]])
print('Yield predicted :',yield_pred[0])
print("Coefficients:",lr.coef_)
print('Intercepts:',lr.intercept_)
print("feature has the highest positive coefficient :",X.columns[lr.coef_.argmax()])